export const Channels = {
  files: {
    read: 'files:read',
    write: 'files:write',
    writeBinary: 'files:writeBinary',
    readBinary: 'files:readBinary',
    edit: 'files:edit',
    ls: 'files:ls',
    mkdir: 'files:mkdir',
    remove: 'files:remove',
    find: 'files:find',
    grep: 'files:grep',
  },
  sql: {
    run: 'sql:run',
  },
  tabs: {
    getTabs: 'tabs:getTabs',
    openTab: 'tabs:openTab',
    closeTab: 'tabs:closeTab',
    selectTab: 'tabs:selectTab',
    reloadTab: 'tabs:reloadTab',
    captureTab: 'tabs:captureTab',
    getConsoleLogs: 'tabs:getConsoleLogs',
    execJs: 'tabs:execJs',
    mountView: 'tabs:mountView',
    updateViewBounds: 'tabs:updateViewBounds',
    destroyView: 'tabs:destroyView',
    showContextMenu: 'tabs:showContextMenu',
    viewEvent: 'tabs:viewEvent',
    stateChanged: 'tabs:stateChanged',
    getState: 'tabs:getState',
    reorderTabs: 'tabs:reorderTabs',
    togglePin: 'tabs:togglePin',
    revealTab: 'tabs:revealTab',
    toggleDevTools: 'tabs:toggleDevTools',
  },
  sessions: {
    list: 'sessions:list',
    read: 'sessions:read',
    write: 'sessions:write',
  },
  store: {
    get: 'store:get',
    set: 'store:set',
    remove: 'store:remove',
  },
  dialog: {
    open: 'dialog:open',
    openExternal: 'dialog:openExternal',
  },
  bus: {
    publish: 'bus:publish',
    waitFor: 'bus:waitFor',
    waitForResolved: 'bus:waitForResolved',
    forwardPublish: 'bus:forwardPublish',
    forwardWaitFor: 'bus:forwardWaitFor',
    forwardSubscribe: 'bus:forwardSubscribe',
    forwardUnsubscribe: 'bus:forwardUnsubscribe',
    subscribeEvent: 'bus:subscribeEvent',
  },
  db: {
    changed: 'db:changed',
  },
  tasks: {
    start: 'tasks:start',
    stop: 'tasks:stop',
    listRunning: 'tasks:listRunning',
    listLogHistory: 'tasks:listLogHistory',
    listLogs: 'tasks:listLogs',
    readLog: 'tasks:readLog',
    writeLog: 'tasks:writeLog',
  },
  plugins: {
    call: 'plugin:call',
    methods: 'plugin:methods',
    install: 'plugin:install',
    uninstall: 'plugin:uninstall',
    requestInstall: 'plugin:requestInstall',
    requestToggle: 'plugin:requestToggle',
    requestUninstall: 'plugin:requestUninstall',
  },
  providers: {
    list: 'provider:list',
    getStatusLine: 'provider:get-status-line',
  },
  runtimeFunctions: {
    methods: 'runtime-functions:methods',
    call: 'runtime-functions:call',
  },
  agent: {
    createSession: 'agent:createSession',
    sendMessage: 'agent:sendMessage',
    abort: 'agent:abort',
    closeSession: 'agent:closeSession',
    loadSession: 'agent:loadSession',
    switchTo: 'agent:switchTo',
    getSessionList: 'agent:getSessionList',
    setNotifyOnFinish: 'agent:setNotifyOnFinish',
    reconnect: 'agent:reconnect',
    getSnapshot: 'agent:getSnapshot',
    snapshot: 'agent:snapshot',
    streaming: 'agent:streaming',
    spawnSession: 'agent:spawnSession',
    sendToSession: 'agent:sendToSession',
    disposeSession: 'agent:disposeSession',
    retryNow: 'agent:retryNow',
  },
  agents: {
    requestInstall: 'agents:requestInstall',
  },
  zenMode: {
    changed: 'zenMode:changed',
  },
  agentSidebar: {
    getInstalled: 'agent-sidebar:getInstalled',
    switch: 'agent-sidebar:switch',
    add: 'agent-sidebar:add',
    addFromFile: 'agent-sidebar:addFromFile',
    remove: 'agent-sidebar:remove',
    switched: 'agent-sidebar:switched',
    showContextMenu: 'agent-sidebar:showContextMenu',
    reorder: 'agent-sidebar:reorder',
  },
} as const;
