export const Channels = {
  sql: {
    run: 'sql:run',
  },
  tabs: {
    openTab: 'tabs:openTab',
    closeTab: 'tabs:closeTab',
    selectTab: 'tabs:selectTab',
    updateViewBounds: 'tabs:updateViewBounds',
    showContextMenu: 'tabs:showContextMenu',
    viewEvent: 'tabs:viewEvent',
    stateChanged: 'tabs:stateChanged',
    getState: 'tabs:getState',
    reorderTabs: 'tabs:reorderTabs',
    togglePin: 'tabs:togglePin',
    revealTab: 'tabs:revealTab',
    toggleDevTools: 'tabs:toggleDevTools',
  },
  sessions: {
    list: 'sessions:list',
    read: 'sessions:read',
    write: 'sessions:write',
  },
  store: {
    get: 'store:get',
    set: 'store:set',
    remove: 'store:remove',
  },
  dialog: {
    open: 'dialog:open',
    openExternal: 'dialog:openExternal',
  },
  db: {
    changed: 'db:changed',
  },
  tasks: {
    start: 'tasks:start',
    stop: 'tasks:stop',
    listRunning: 'tasks:listRunning',
    listLogHistory: 'tasks:listLogHistory',
    listLogs: 'tasks:listLogs',
    readLog: 'tasks:readLog',
    writeLog: 'tasks:writeLog',
    runFinished: 'tasks:runFinished',
    runStarted: 'tasks:runStarted',
  },
  providers: {
    list: 'provider:list',
    getStatusLine: 'provider:get-status-line',
    switchProvider: 'provider:switch-provider',
    setDefault: 'provider:set-default',
    stateChanged: 'provider:state-changed',
  },
  runtimeFunctions: {
    methods: 'runtime-functions:methods',
    call: 'runtime-functions:call',
  },
  agent: {
    createSession: 'agent:createSession',
    sendMessage: 'agent:sendMessage',
    abort: 'agent:abort',
    closeSession: 'agent:closeSession',
    loadSession: 'agent:loadSession',
    switchTo: 'agent:switchTo',
    getSessionList: 'agent:getSessionList',
    setNotifyOnFinish: 'agent:setNotifyOnFinish',
    reconnect: 'agent:reconnect',
    getSnapshot: 'agent:getSnapshot',
    snapshot: 'agent:snapshot',
    streaming: 'agent:streaming',
    spawnSession: 'agent:spawnSession',
    sendToSession: 'agent:sendToSession',
    disposeSession: 'agent:disposeSession',
    retryNow: 'agent:retryNow',
  },
  agents: {
    requestInstall: 'agents:requestInstall',
  },
  views: {
    fetch: 'views:fetch',
  },
  zenMode: {
    toggle: 'zenMode:toggle',
    set: 'zenMode:set',
    changed: 'zenMode:changed',
  },
  agentSidebar: {
    getInstalled: 'agent-sidebar:getInstalled',
    switch: 'agent-sidebar:switch',
    add: 'agent-sidebar:add',
    addFromFile: 'agent-sidebar:addFromFile',
    remove: 'agent-sidebar:remove',
    switched: 'agent-sidebar:switched',
    showContextMenu: 'agent-sidebar:showContextMenu',
    reorder: 'agent-sidebar:reorder',
  },
} as const;
