export const Channels = {
  files: {
    read: 'files:read',
    write: 'files:write',
    writeBinary: 'files:writeBinary',
    edit: 'files:edit',
    ls: 'files:ls',
    mkdir: 'files:mkdir',
    remove: 'files:remove',
    find: 'files:find',
    grep: 'files:grep',
  },
  sql: {
    run: 'sql:run',
  },
  tabs: {
    getTabs: 'tabs:getTabs',
    openTab: 'tabs:openTab',
    closeTab: 'tabs:closeTab',
    selectTab: 'tabs:selectTab',
    reloadTab: 'tabs:reloadTab',
    captureTab: 'tabs:captureTab',
    getConsoleLogs: 'tabs:getConsoleLogs',
    execJs: 'tabs:execJs',
    mountView: 'tabs:mountView',
    updateViewBounds: 'tabs:updateViewBounds',
    destroyView: 'tabs:destroyView',
    showContextMenu: 'tabs:showContextMenu',
    viewEvent: 'tabs:viewEvent',
  },
  sessions: {
    list: 'sessions:list',
    read: 'sessions:read',
    write: 'sessions:write',
  },
  store: {
    get: 'store:get',
    set: 'store:set',
    remove: 'store:remove',
  },
  dialog: {
    open: 'dialog:open',
    openExternal: 'dialog:openExternal',
  },
  bus: {
    publish: 'bus:publish',
    waitFor: 'bus:waitFor',
    waitForResolved: 'bus:waitForResolved',
    forwardPublish: 'bus:forwardPublish',
    forwardWaitFor: 'bus:forwardWaitFor',
    forwardSubscribe: 'bus:forwardSubscribe',
    forwardUnsubscribe: 'bus:forwardUnsubscribe',
    subscribeEvent: 'bus:subscribeEvent',
    forwardSpawnAgent: 'bus:forwardSpawnAgent',
    spawnAgentResult: 'bus:spawnAgentResult',
    spawnAgent: 'bus:spawnAgent',
    forwardSendToAgent: 'bus:forwardSendToAgent',
    sendToAgentResult: 'bus:sendToAgentResult',
    sendToAgent: 'bus:sendToAgent',
    dbChanged: 'bus:dbChanged',
  },
  headers: {
    set: 'headers:set',
  },
  tasks: {
    start: 'tasks:start',
    stop: 'tasks:stop',
    listLogHistory: 'tasks:listLogHistory',
    listLogs: 'tasks:listLogs',
    readLog: 'tasks:readLog',
    writeLog: 'tasks:writeLog',
    forwardStart: 'tasks:forwardStart',
    forwardStartResult: 'tasks:forwardStartResult',
    forwardStop: 'tasks:forwardStop',
    forwardStopResult: 'tasks:forwardStopResult',
  },
  plugins: {
    call: 'plugin:call',
    methods: 'plugin:methods',
    install: 'plugin:install',
    uninstall: 'plugin:uninstall',
  },
  providers: {
    list: 'provider:list',
    getStatusLine: 'provider:get-status-line',
    createSession: 'provider:create-session',
    restoreSession: 'provider:restore-session',
    send: 'provider:send',
    event: 'provider:event',
    getDisplayMessages: 'provider:get-display-messages',
  },
} as const;
