export const Channels = {
  sql: {
    run: 'sql:run',
  },
  tabs: {
    openTab: 'tabs:openTab',
    closeTab: 'tabs:closeTab',
    selectTab: 'tabs:selectTab',
    updateViewBounds: 'tabs:updateViewBounds',
    showContextMenu: 'tabs:showContextMenu',
    viewEvent: 'tabs:viewEvent',
    stateChanged: 'tabs:stateChanged',
    getState: 'tabs:getState',
    getHeadlessCount: 'tabs:getHeadlessCount',
    reorderTabs: 'tabs:reorderTabs',
    togglePin: 'tabs:togglePin',
    toggleDevTools: 'tabs:toggleDevTools',
    describe: 'tabs:describe',
  },
  store: {
    get: 'store:get',
    set: 'store:set',
    remove: 'store:remove',
  },
  dialog: {
    open: 'dialog:open',
    openExternal: 'dialog:openExternal',
  },
  db: {
    changed: 'db:changed',
  },
  tasks: {
    start: 'tasks:start',
    stop: 'tasks:stop',
    listRunning: 'tasks:listRunning',
    readRun: 'tasks:readRun',
    listLogHistory: 'tasks:listLogHistory',
    readLog: 'tasks:readLog',
    runFinished: 'tasks:runFinished',
    runStarted: 'tasks:runStarted',
    runLog: 'tasks:runLog',
    listShortcuts: 'tasks:listShortcuts',
  },
  providers: {
    list: 'provider:list',
    getStatusLine: 'provider:get-status-line',
    setDefault: 'provider:set-default',
    stateChanged: 'provider:state-changed',
  },
  runtimeFunctions: {
    methods: 'runtime-functions:methods',
    call: 'runtime-functions:call',
  },
  agent: {
    createSession: 'agent:createSession',
    sendMessage: 'agent:sendMessage',
    abort: 'agent:abort',
    closeSession: 'agent:closeSession',
    loadSession: 'agent:loadSession',
    switchTo: 'agent:switchTo',
    getSessionList: 'agent:getSessionList',
    setNotifyOnFinish: 'agent:setNotifyOnFinish',
    reconnect: 'agent:reconnect',
    getSnapshot: 'agent:getSnapshot',
    snapshot: 'agent:snapshot',
    streaming: 'agent:streaming',
    unloadSession: 'agent:unloadSession',
    retryNow: 'agent:retryNow',
  },
  agents: {
    requestInstall: 'agents:requestInstall',
  },
  views: {
    fetch: 'views:fetch',
  },
  previewCursor: {
    setPos: 'previewCursor:setPos',
    setVisible: 'previewCursor:setVisible',
    flash: 'previewCursor:flash',
  },
  zenMode: {
    toggle: 'zenMode:toggle',
    set: 'zenMode:set',
    changed: 'zenMode:changed',
  },
  agentSidebar: {
    getInstalled: 'agent-sidebar:getInstalled',
    switch: 'agent-sidebar:switch',
    add: 'agent-sidebar:add',
    addFromFile: 'agent-sidebar:addFromFile',
    remove: 'agent-sidebar:remove',
    stop: 'agent-sidebar:stop',
    switched: 'agent-sidebar:switched',
    showContextMenu: 'agent-sidebar:showContextMenu',
    reorder: 'agent-sidebar:reorder',
  },
  traces: {
    list: 'traces:list',
  },
  app: {
    restart: 'app:restart',
    stop: 'app:stop',
    reloadRenderer: 'app:reloadRenderer',
    getAgentId: 'app:getAgentId',
    openAgentDir: 'app:openAgentDir',
    getAgentDisplayPath: 'app:getAgentDisplayPath',
    getHttpApiPort: 'app:getHttpApiPort',
    getBackupStatus: 'app:getBackupStatus',
    getDefaultView: 'app:getDefaultView',
    getSetting: 'app:getSetting',
    settingChanged: 'app:settingChanged',
  },
} as const;
