[package]
name = "agentwfy-mobile"
version = "0.1.0"
description = "AgentWFY mobile client"
authors = ["endenwer"]
edition = "2021"

[lib]
name = "agentwfy_mobile_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
tauri = { version = "2.11.2", features = [] }
