// AUTO-GENERATED by scripts/build from src/system-config/system-config.json
// DO NOT EDIT — your changes will be overwritten on the next build.

export const SYSTEM_PREFIX = 'system.'
export const PLUGIN_PREFIX = 'plugin.'
export const SHORTCUT_PREFIX = 'system.shortcuts.'
export const OPENAI_COMPATIBLE_PREFIX = 'system.openai-compatible-provider'

export const SystemConfigKeys = {
  theme: "system.theme",
  defaultView: "system.default-view",
  backupIntervalHours: "system.backup.interval-hours",
  backupMaxCount: "system.backup.max-count",
  cleanupSessionRetentionDays: "system.cleanup.session-retention-days",
  cleanupTaskLogRetentionDays: "system.cleanup.task-log-retention-days",
  cleanupTraceRetentionDays: "system.cleanup.trace-retention-days",
  httpApiPort: "system.http-api.port",
  provider: "system.provider",
  openaiCompatibleProviderApiKey: "system.openai-compatible-provider.api-key",
  openaiCompatibleProviderModelId: "system.openai-compatible-provider.model-id",
  openaiCompatibleProviderBaseUrl: "system.openai-compatible-provider.base-url",
  openaiCompatibleProviderReasoning: "system.openai-compatible-provider.reasoning",
  showTabSource: "system.show-tab-source",
  shortcutsToggleCommandPalette: "system.shortcuts.toggle-command-palette",
  shortcutsToggleAgentChat: "system.shortcuts.toggle-agent-chat",
  shortcutsToggleTaskPanel: "system.shortcuts.toggle-task-panel",
  shortcutsCloseCurrentTab: "system.shortcuts.close-current-tab",
  shortcutsReloadCurrentTab: "system.shortcuts.reload-current-tab",
  shortcutsReloadWindow: "system.shortcuts.reload-window",
  shortcutsAddAgent: "system.shortcuts.add-agent",
  shortcutsNewSession: "system.shortcuts.new-session",
  shortcutsSwitchToTab1: "system.shortcuts.switch-to-tab-1",
  shortcutsSwitchToTab2: "system.shortcuts.switch-to-tab-2",
  shortcutsSwitchToTab3: "system.shortcuts.switch-to-tab-3",
  shortcutsSwitchToTab4: "system.shortcuts.switch-to-tab-4",
  shortcutsSwitchToTab5: "system.shortcuts.switch-to-tab-5",
  shortcutsSwitchToTab6: "system.shortcuts.switch-to-tab-6",
  shortcutsSwitchToTab7: "system.shortcuts.switch-to-tab-7",
  shortcutsSwitchToTab8: "system.shortcuts.switch-to-tab-8",
  shortcutsSwitchToTab9: "system.shortcuts.switch-to-tab-9",
  shortcutsPreviousTab: "system.shortcuts.previous-tab",
  shortcutsNextTab: "system.shortcuts.next-tab",
  shortcutsNextAgent: "system.shortcuts.next-agent",
  shortcutsPreviousAgent: "system.shortcuts.previous-agent",
  shortcutsSearchViews: "system.shortcuts.search-views",
  shortcutsOpenTabsList: "system.shortcuts.open-tabs-list",
  shortcutsOpenSettings: "system.shortcuts.open-settings",
  shortcutsToggleDevTools: "system.shortcuts.toggle-dev-tools",
  hideAgentSidebar: "system.hide-agent-sidebar",
  hidePanelSwitcher: "system.hide-panel-switcher",
  hidePanelToggle: "system.hide-panel-toggle",
  hideStatusLine: "system.hide-status-line",
  hideTabs: "system.hide-tabs",
  hideTrafficLights: "system.hide-traffic-lights",
} as const

export type SystemConfigKey = typeof SystemConfigKeys[keyof typeof SystemConfigKeys]
